### ISSUE TITLE
TypeError in MethodScheduler

### ISSUE THREAD

**Issue by theresagun** [RedFox95/DTRmscsProject#10]
I ran the app.py file and got this error:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Users/tmg/Documents/cs710/DTRmscsProject/backend/metrics/MethodScheduler.py", line 14, in run
    self._target_method()
  File "/Users/tmg/Documents/cs710/DTRmscsProject/app.py", line 50, in collect_metrics
    db.addProcessMetrics(process['pid'], process['name'], process['cpu_times'][1],
                                                          ~~~~~~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
```
Using a mac

**Comment by theresagun** [comment]
Closed with #16
